version: '3'
services:
  app:
    container_name: books-backend
    build: .
    ports:
      - '3000:3000'
    external_links:
      - mongodb2
  mongodb:
    container_name: mongodb2
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
